//! Golden test for the `conv_1d` kernel: bit-exact comparison against
//! fixtures generated by the naive reference implementation
//! (`cargo run --example golden_gen`, seed 42).
//!
//! The dispatch table below mirrors the shape grid of the generator;
//! a fixture with an unknown shape fails loudly instead of being skipped.

use microflow::activation::FusedActivation;
use microflow::buffer::Buffer2D;
use microflow::ops::{conv_1d, Conv1DOptions};
use microflow::tensor::{Tensor2D, Tensor4D, TensorViewPadding};

struct Case {
    id: usize,
    t: usize,
    c: usize,
    k: usize,
    f: usize,
    stride: usize,
    same: bool,
    relu: bool,
    scale_x: f32,
    zp_x: i8,
    scale_out: f32,
    zp_out: i8,
    filter_scales: Vec<f32>,
    input: Vec<i8>,
    weights: Vec<i8>,
    bias: Vec<i32>,
    expected: Vec<i8>,
}

#[derive(PartialEq)]
enum Section {
    None,
    FilterScales,
    Input,
    Weights,
    Bias,
    Expected,
}

fn parse_cases(text: &str) -> Vec<Case> {
    let mut cases = Vec::new();
    let mut case = Case {
        id: 0,
        t: 0,
        c: 0,
        k: 0,
        f: 0,
        stride: 0,
        same: false,
        relu: false,
        scale_x: 0.,
        zp_x: 0,
        scale_out: 0.,
        zp_out: 0,
        filter_scales: Vec::new(),
        input: Vec::new(),
        weights: Vec::new(),
        bias: Vec::new(),
        expected: Vec::new(),
    };
    let mut section = Section::None;
    for (number, line) in text.lines().enumerate() {
        let line = line.split('#').next().unwrap().trim();
        if line.is_empty() {
            continue;
        }
        let line_number = number + 1;
        let report = |message: &str| format!("line {line_number}: {message}");
        let tokens: Vec<&str> = line.split_whitespace().collect();
        match tokens[0] {
            "case" => {
                if case.t > 0 {
                    cases.push(case);
                }
                let parse = |i: usize| {
                    tokens[i]
                        .parse::<usize>()
                        .unwrap_or_else(|e| panic!("{}", report(&format!("bad int: {e}"))))
                };
                case = Case {
                    id: cases.len() + 1,
                    t: parse(1),
                    c: parse(2),
                    k: parse(3),
                    f: parse(4),
                    stride: parse(5),
                    same: tokens[6] == "same",
                    relu: tokens[7] == "relu",
                    scale_x: 0.,
                    zp_x: 0,
                    scale_out: 0.,
                    zp_out: 0,
                    filter_scales: Vec::new(),
                    input: Vec::new(),
                    weights: Vec::new(),
                    bias: Vec::new(),
                    expected: Vec::new(),
                };
                section = Section::None;
            }
            "quant" => {
                case.scale_x = parse_float(tokens[1], &report);
                case.zp_x = parse_int(tokens[2], &report);
                case.scale_out = parse_float(tokens[3], &report);
                case.zp_out = parse_int(tokens[4], &report);
            }
            "filter_scales" => {
                section = Section::FilterScales;
                case.filter_scales
                    .extend(tokens[1..].iter().map(|t| parse_float(t, &report)));
            }
            "input" => section = Section::Input,
            "weights" => section = Section::Weights,
            "bias" => {
                section = Section::Bias;
                case.bias.extend(tokens[1..].iter().map(|token| {
                    token
                        .parse::<i32>()
                        .unwrap_or_else(|e| panic!("{}", report(&format!("bad bias {token}: {e}"))))
                }));
            }
            "expected" => section = Section::Expected,
            _ => match section {
                Section::None => panic!("{}", report("value outside any section")),
                Section::FilterScales => {
                    case.filter_scales
                        .extend(tokens.iter().map(|t| parse_float(t, &report)));
                }
                Section::Input => extend_ints(&mut case.input, &tokens, &report),
                Section::Weights => extend_ints(&mut case.weights, &tokens, &report),
                Section::Bias => {
                    case.bias.extend(tokens.iter().map(|token| {
                        token.parse::<i32>().unwrap_or_else(|e| {
                            panic!("{}", report(&format!("bad bias {token}: {e}")))
                        })
                    }));
                }
                Section::Expected => extend_ints(&mut case.expected, &tokens, &report),
            },
        }
    }
    if case.t > 0 {
        cases.push(case);
    }
    cases
}

fn parse_float(token: &str, report: &dyn Fn(&str) -> String) -> f32 {
    token
        .parse::<f32>()
        .unwrap_or_else(|e| panic!("{}", report(&format!("bad float {token}: {e}"))))
}

fn parse_int(token: &str, report: &dyn Fn(&str) -> String) -> i8 {
    token
        .parse::<i8>()
        .unwrap_or_else(|e| panic!("{}", report(&format!("bad int {token}: {e}"))))
}

fn extend_ints(target: &mut Vec<i8>, tokens: &[&str], report: &dyn Fn(&str) -> String) {
    target.extend(tokens.iter().map(|t| parse_int(t, report)));
}

macro_rules! run_case {
    ($case:expr, $t:literal, $c:literal, $k:literal, $f:literal, $out:literal) => {{
        let case: &Case = $case;
        assert_eq!(case.input.len(), $t * $c, "case {}: input size", case.id);
        assert_eq!(
            case.weights.len(),
            $f * $k * $c,
            "case {}: weights size",
            case.id
        );
        assert_eq!(case.filter_scales.len(), $f, "case {}: scales", case.id);
        assert_eq!(case.bias.len(), $f, "case {}: bias", case.id);
        assert_eq!(
            case.expected.len(),
            $out * $f,
            "case {}: expected size",
            case.id
        );
        let input = Tensor4D::<i8, 1, 1, $t, $c, 1>::new(
            [Buffer2D::from_fn(|_, t| {
                core::array::from_fn(|c| case.input[t * $c + c])
            })],
            [case.scale_x],
            [case.zp_x],
        );
        let filter_scales: [f32; $f] = case.filter_scales.clone().try_into().unwrap();
        let filters = Tensor4D::<i8, $f, 1, $k, $c, $f>::new(
            core::array::from_fn(|f| {
                Buffer2D::from_fn(|_, m| {
                    core::array::from_fn(|c| case.weights[(f * $k + m) * $c + c])
                })
            }),
            filter_scales,
            [0; $f],
        );
        let biases = Tensor2D::<i32, $f, 1, $f>::new(
            Buffer2D::from_fn(|f, _| case.bias[f]),
            [0.; $f],
            [0; $f],
        );
        let output = conv_1d::<i8, $t, $c, $k, $f, $f, $out>(
            input,
            &filters,
            &biases,
            [case.scale_out],
            [case.zp_out],
            Conv1DOptions {
                fused_activation: if case.relu {
                    FusedActivation::Relu
                } else {
                    FusedActivation::None
                },
                padding: if case.same {
                    TensorViewPadding::Same
                } else {
                    TensorViewPadding::Valid
                },
                stride: case.stride,
            },
        );
        for t in 0..$out {
            for f in 0..$f {
                assert_eq!(
                    output.buffer[0][(0, t)][f],
                    case.expected[t * $f + f],
                    "case {}: t={t}, f={f}",
                    case.id
                );
            }
        }
    }};
}

#[test]
fn conv_1d_matches_golden_fixtures() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/conv1d.txt");
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let cases = parse_cases(&text);
    assert!(
        cases.len() >= 90,
        "expected ~100 golden cases, got {}",
        cases.len()
    );
    for case in &cases {
        let shape = (case.t, case.c, case.k, case.f, case.stride, case.same);
        match shape {
            (5, 1, 3, 1, 1, false) => run_case!(case, 5, 1, 3, 1, 3),
            (5, 1, 3, 1, 1, true) => run_case!(case, 5, 1, 3, 1, 5),
            (4, 1, 2, 2, 1, false) => run_case!(case, 4, 1, 2, 2, 3),
            (8, 2, 3, 4, 1, true) => run_case!(case, 8, 2, 3, 4, 8),
            (8, 2, 3, 4, 2, true) => run_case!(case, 8, 2, 3, 4, 4),
            (16, 4, 3, 4, 2, false) => run_case!(case, 16, 4, 3, 4, 7),
            (7, 8, 5, 8, 1, true) => run_case!(case, 7, 8, 5, 8, 7),
            (64, 8, 7, 16, 2, true) => run_case!(case, 64, 8, 7, 16, 32),
            (2, 1, 3, 1, 1, true) => run_case!(case, 2, 1, 3, 1, 2),
            (1, 1, 1, 1, 1, false) => run_case!(case, 1, 1, 1, 1, 1),
            (3, 2, 1, 2, 2, false) => run_case!(case, 3, 2, 1, 2, 2),
            (63, 1, 7, 1, 2, false) => run_case!(case, 63, 1, 7, 1, 29),
            other => panic!("unknown shape {other:?} — extend the dispatch table"),
        }
    }
}
